# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Artem Tomilo
first_name: Artem
middle_name:
last_name: Tomilo
email: artem.tomilo@math.uoc.gr
description: Personal website of Artem Tomilo
show_downloads: true
keywords: jekyll, jekyll-theme, academic-website, portfolio-website 

lang: en
icon: ⚛️

url: https://artetom.github.io 
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
